[package]
name = "in_one_weekend"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[dependencies]
log = "0.4"
env_logger = "0.10"
rand = "0.8"
fastrand = "1.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "random"
harness = false

